baseURL = 'https://funinkina.xyz/'
languageCode = 'en-us'
title = "funinkina's blogs"
theme = 'hugo-dead-simple'
googleAnalytics = "G-KN1LB8C8L2"

[params.google.analytics]
id = "G-KN1LB8C8L2"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
author = "Aryan Kushwaha"
description = "A portfolio and blog by Aryan Kushwaha"
ShowReadingTime = true
ShowDate = true
favicon = "favicon.ico"

[permalinks]
blog = "/blog/:slug/"


[menu]
[[menu.main]]
name = "ğŸ  Home"
url = "/"
weight = 1
[[menu.main]]
name = "ğŸ“ Blogs"
url = "/blog/"
weight = 2
[[menu.main]]
name = "ğŸ“¡ RSS Feed"
url = "/index.xml"
weight = 3
