baseURL = 'https://funinkina.is-a.dev/'
languageCode = 'en-us'
title = "funinkina's blogs"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
author = "Aryan Kushwaha"
description = "A portfolio and blog by Aryan Kushwaha"
ShowReadingTime = true
ShowDate = true
favicon = "favicon.ico"

[params.vercel_analytics]
enable = true

[permalinks]
blog = "/blog/:slug/"

[menu]
[[menu.main]]
name = "HOME"
url = "/"
weight = 1
[[menu.main]]
name = "BLOGS"
url = "/blog/"
weight = 2
[[menu.main]]
name = "PROJECTS"
url = "/projects/"
weight = 3
[[menu.main]]
name = "RSS FEED"
url = "/index.xml"
weight = 4
